package com.example.ui.util

object Strings {
    private val pl = mapOf(
        "about" to "O programie",
        "about_desc" to "rBiblia to wieloprzekładowy czytnik Pisma Świętego z zaawansowaną porównywarką wersetów, czytaniem równoległym, notatkami i szybkim wyszukiwaniem.",
        "add_note" to "Dodaj notatkę",
        "all_translations" to "Wszystkie tłumaczenia",
        "cancel" to "Anuluj",
        "chapter_comparison" to "Porównanie rozdziałów",
        "clear_history" to "Wyczyść historię",
        "compare_verse" to "Porównaj werset",
        "copied" to "Skopiowano do schowka",
        "copy_report" to "Kopiuj zgłoszenie",
        "dark_variant" to "Wariant ciemnego motywu",
        "delete" to "Usuń",
        "deuterocanonical" to "Księgi deuterokanoniczne",
        "edit_note" to "Edytuj notatkę",
        "error_type" to "Rodzaj błędu",
        "favorites" to "Ulubione",
        "font_family" to "Krój czcionki",
        "global_note" to "Notatka ogólna (dla wszystkich przekładów)",
        "hide" to "Ukryj",
        "language" to "Język aplikacji",
        "layout_continuous" to "Tekst ciągły",
        "layout_split" to "Podział na wersety",
        "new_testament" to "Nowy Testament",
        "next_chapter" to "Następny rozdział",
        "no_results" to "Brak wyników wyszukiwania",
        "note_placeholder" to "Wpisz treść notatki...",
        "notes" to "Notatki",
        "old_testament" to "Stary Testament",
        "prev_chapter" to "Poprzedni rozdział",
        "recent_searches" to "Ostatnie wyszukiwania",
        "report_comment" to "Komentarz / opis błędu",
        "reporter_email" to "Twój e-mail (opcjonalnie)",
        "reporter_name" to "Twoje imię / nick",
        "report_error" to "Zgłoś błąd w tekście",
        "results_found" to "Znaleziono",
        "save_note" to "Zapisz notatkę",
        "search" to "Szukaj w Biblii",
        "search_hint" to "Wpisz szukane słowo lub frazę...",
        "select_book" to "Wybierz księgę",
        "select_chapter" to "Wybierz rozdział",
        "settings" to "Ustawienia",
        "show" to "Pokaż",
        "show_differences" to "Wyróżnij różnice między przekładami",
        "submit_report" to "Wyślij zgłoszenie",
        "suggested_text" to "Poprawny tekst wersetu",
        "text_size" to "Rozmiar tekstu",
        "theme" to "Motyw kolorystyczny",
        "translations" to "Przekłady Biblii",
        "type_inaccuracy" to "Niedokładność tłumaczenia",
        "type_missing" to "Brakujący fragment",
        "type_punct" to "Błąd interpunkcyjny",
        "type_typo" to "Literówka / błąd ortograficzny",
        "verse_layout" to "Układ tekstu",
        "verse_numbers" to "Numery wersetów",
        "zen_mode" to "Tryb Zen (pełny ekran)",
        "zen_mode_hint" to "Maksymalna przestrzeń do czytania bez rozpraszaczy",
        "lang_all" to "Wszystkie",
        "lang_pl" to "Polski",
        "lang_en" to "English",
        "lang_de" to "Deutsch",
        "filter_by_language" to "Język przekładu",
        "parallel_reading" to "Czytanie równoległe",
        "parallel_mode_hint" to "Porównuj dwa przekłady symultanicznie",
        "select_parallel_translation" to "Wybierz drugi przekład",
        "parallel_columns" to "Dwie kolumny",
        "parallel_stacked" to "Wiersz pod wierszem",
        "swap_translations" to "Zamień przekłady",
        "parallel_missing_book" to "Ten przekład nie zawiera bieżącej księgi",
        "highlight_diff" to "Różnice",
        "verse_not_found_in_translation" to "Werset nie został znaleziony w tym tłumaczeniu",
        "previous_verse" to "Poprzedni werset",
        "next_verse" to "Następny werset",
        "add_comparison" to "Dodaj przekład",
        "current_translation" to "Bieżące",
        "compare_with" to "Porównaj z",
        "diff_mode" to "Tryb wyróżniania różnic",
        "diff_mode_loose" to "Luźny (dowolny szyk)",
        "diff_mode_strict" to "Ścisły (kolejność słów)",
        "export_notes_xml" to "Eksportuj notatki (XML)",
        "import_notes_xml" to "Importuj notatki (XML)",
        "notes_exported" to "Skopiowano XML notatek do schowka",
        "notes_imported" to "Pomyślnie zaimportowano notatki",
        "remove_from_comparison" to "Usuń z porównania",
        "offline_cache" to "Pamięć podręczna offline (Room)",
        "cached_verses_count" to "Wersetów w pamięci offline",
        "clear_cache" to "Wyczyść pamięć podręczną",
        "cache_cleared" to "Pamięć podręczna Room została wyczyszczona",
        "download_book_offline" to "Pobierz tę księgę do trybu offline",
        "downloading_offline" to "Pobieranie rozdziałów do bazy offline...",
        "book_downloaded" to "Księga została zapisana w bazie offline",
        "check_updates" to "Sprawdź aktualizacje z GitHub",
        "checking_updates" to "Sprawdzanie aktualizacji...",
        "update_available" to "Nowa wersja dostępna!",
        "up_to_date" to "Posiadasz najnowszą wersję aplikacji",
        "download_update" to "Pobierz i zaktualizuj (APK)",
        "release_notes" to "Lista zmian",
        "comparison_count" to "Liczba porównywanych przekładów (2-6):"
    )

    private val en = mapOf(
        "about" to "About",
        "about_desc" to "rBiblia is a multi-translation Holy Bible reader with verse comparison, parallel reading, personal notes, and fast search.",
        "add_note" to "Add Note",
        "all_translations" to "All Translations",
        "cancel" to "Cancel",
        "chapter_comparison" to "Chapter Comparison",
        "clear_history" to "Clear History",
        "compare_verse" to "Compare Verse",
        "copied" to "Copied to clipboard",
        "copy_report" to "Copy Report",
        "dark_variant" to "Dark Theme Style",
        "delete" to "Delete",
        "deuterocanonical" to "Deuterocanonical",
        "edit_note" to "Edit Note",
        "error_type" to "Error Type",
        "favorites" to "Favorites",
        "font_family" to "Font Family",
        "global_note" to "Global Note (for all translations)",
        "hide" to "Hide",
        "language" to "App Language",
        "layout_continuous" to "Continuous Text",
        "layout_split" to "Verse by Verse",
        "new_testament" to "New Testament",
        "next_chapter" to "Next Chapter",
        "no_results" to "No results found",
        "note_placeholder" to "Write your note here...",
        "notes" to "Notes",
        "old_testament" to "Old Testament",
        "prev_chapter" to "Previous Chapter",
        "recent_searches" to "Recent Searches",
        "report_comment" to "Notes / Comments",
        "reporter_email" to "Your Email (optional)",
        "reporter_name" to "Your Name / Nickname",
        "report_error" to "Report Text Error",
        "results_found" to "Results found",
        "save_note" to "Save Note",
        "search" to "Search Bible",
        "search_hint" to "Search for word or phrase...",
        "select_book" to "Select Book",
        "select_chapter" to "Select Chapter",
        "settings" to "Settings",
        "show" to "Show",
        "show_differences" to "Highlight Differences",
        "submit_report" to "Submit Report",
        "suggested_text" to "Suggested Correct Text",
        "text_size" to "Text Size",
        "theme" to "Color Theme",
        "translations" to "Bible Translations",
        "type_inaccuracy" to "Translation Inaccuracy",
        "type_missing" to "Missing Text",
        "type_punct" to "Punctuation Error",
        "type_typo" to "Typo / Spelling",
        "verse_layout" to "Verse Layout",
        "verse_numbers" to "Verse Numbers",
        "zen_mode" to "Zen Mode",
        "zen_mode_hint" to "Minimalist reading experience",
        "lang_all" to "All",
        "lang_pl" to "Polish",
        "lang_en" to "English",
        "lang_de" to "German",
        "filter_by_language" to "Translation Language",
        "parallel_reading" to "Parallel Reading",
        "parallel_mode_hint" to "Read two translations side-by-side",
        "select_parallel_translation" to "Select Second Translation",
        "parallel_columns" to "Two Columns",
        "parallel_stacked" to "Stacked Rows",
        "swap_translations" to "Swap Translations",
        "parallel_missing_book" to "This translation does not contain current book",
        "highlight_diff" to "Differences",
        "verse_not_found_in_translation" to "Verse not found in this translation",
        "previous_verse" to "Previous verse",
        "next_verse" to "Next verse",
        "add_comparison" to "Add translation",
        "current_translation" to "Current",
        "compare_with" to "Compare with",
        "diff_mode" to "Difference mode",
        "diff_mode_loose" to "Loose (ignore order)",
        "diff_mode_strict" to "Strict (word order)",
        "export_notes_xml" to "Export Notes (XML)",
        "import_notes_xml" to "Import Notes (XML)",
        "notes_exported" to "Notes XML copied to clipboard",
        "notes_imported" to "Notes imported successfully",
        "remove_from_comparison" to "Remove from comparison",
        "offline_cache" to "Offline Cache (Room)",
        "cached_verses_count" to "Cached verses offline",
        "clear_cache" to "Clear offline cache",
        "cache_cleared" to "Offline Room cache cleared",
        "download_book_offline" to "Download current book offline",
        "downloading_offline" to "Downloading chapters to offline database...",
        "book_downloaded" to "Book successfully saved to offline cache",
        "check_updates" to "Check for GitHub updates",
        "checking_updates" to "Checking for updates...",
        "update_available" to "New version available!",
        "up_to_date" to "You have the latest version",
        "download_update" to "Download & Install (APK)",
        "release_notes" to "Release Notes",
        "comparison_count" to "Number of compared translations (2-6):"
    )

    private val de = mapOf(
        "about" to "Über das Programm",
        "about_desc" to "rBiblia ist ein mehrsprachiger Bibel-Reader mit Versvergleich, Parallellesemodus, Notizen und schneller Suche.",
        "add_note" to "Notiz hinzufügen",
        "all_translations" to "Alle Übersetzungen",
        "cancel" to "Abbrechen",
        "chapter_comparison" to "Kapitelvergleich",
        "clear_history" to "Verlauf löschen",
        "compare_verse" to "Vers vergleichen",
        "copied" to "In die Zwischenablage kopiert",
        "copy_report" to "Bericht kopieren",
        "dark_variant" to "Dunkles Design",
        "delete" to "Löschen",
        "deuterocanonical" to "Spätschriften",
        "edit_note" to "Notiz bearbeiten",
        "error_type" to "Fehlertyp",
        "favorites" to "Favoriten",
        "font_family" to "Schriftart",
        "global_note" to "Globale Notiz (für alle Übersetzungen)",
        "hide" to "Ausblenden",
        "language" to "App-Sprache",
        "layout_continuous" to "Fließtext",
        "layout_split" to "Vers für Vers",
        "new_testament" to "Neues Testament",
        "next_chapter" to "Nächstes Kapitel",
        "no_results" to "Keine Ergebnisse gefunden",
        "note_placeholder" to "Notiz eingeben...",
        "notes" to "Notizen",
        "old_testament" to "Altes Testament",
        "prev_chapter" to "Vorheriges Kapitel",
        "recent_searches" to "Letzte Suchen",
        "report_comment" to "Kommentar",
        "reporter_email" to "Ihre E-Mail",
        "reporter_name" to "Ihr Name",
        "report_error" to "Fehler melden",
        "results_found" to "Gefunden",
        "save_note" to "Notiz speichern",
        "search" to "Bibel durchsuchen",
        "search_hint" to "Suchbegriff eingeben...",
        "select_book" to "Buch auswählen",
        "select_chapter" to "Kapitel auswählen",
        "settings" to "Einstellungen",
        "show" to "Anzeigen",
        "show_differences" to "Unterschiede hervorheben",
        "submit_report" to "Bericht senden",
        "suggested_text" to "Korrekturvorschlag",
        "text_size" to "Textgröße",
        "theme" to "Farbthema",
        "translations" to "Bibelübersetzungen",
        "type_inaccuracy" to "Ungenauigkeit",
        "type_missing" to "Fehlender Text",
        "type_punct" to "Satzzeichenfehler",
        "type_typo" to "Tippfehler",
        "verse_layout" to "Textanordnung",
        "verse_numbers" to "Versnummern",
        "zen_mode" to "Zen-Modus",
        "zen_mode_hint" to "Ablenkungsfreies Lesen",
        "lang_all" to "Alle",
        "lang_pl" to "Polnisch",
        "lang_en" to "Englisch",
        "lang_de" to "Deutsch",
        "filter_by_language" to "Sprache der Übersetzung",
        "parallel_reading" to "Paralleles Lesen",
        "parallel_mode_hint" to "Zwei Übersetzungen nebeneinander lesen",
        "select_parallel_translation" to "Zweite Übersetzung wählen",
        "parallel_columns" to "Zwei Spalten",
        "parallel_stacked" to "Zeile unter Zeile",
        "swap_translations" to "Übersetzungen tauschen",
        "parallel_missing_book" to "Diese Übersetzung enthält das aktuelle Buch nicht",
        "highlight_diff" to "Unterschiede",
        "verse_not_found_in_translation" to "Vers in dieser Übersetzung nicht gefunden",
        "previous_verse" to "Vorheriger Vers",
        "next_verse" to "Nächster Vers",
        "add_comparison" to "Übersetzung hinzufügen",
        "current_translation" to "Aktuell",
        "compare_with" to "Vergleichen mit",
        "diff_mode" to "Vergleichsmodus",
        "diff_mode_loose" to "Locker (Reihenfolge ignorieren)",
        "diff_mode_strict" to "Strikt (Wortreihenfolge)",
        "export_notes_xml" to "Notizen exportieren (XML)",
        "import_notes_xml" to "Notizen importieren (XML)",
        "notes_exported" to "Notizen XML in Zwischenablage kopiert",
        "notes_imported" to "Notizen erfolgreich importiert",
        "remove_from_comparison" to "Aus dem Vergleich entfernen",
        "offline_cache" to "Offline-Cache (Room)",
        "cached_verses_count" to "Verse im Offline-Cache",
        "clear_cache" to "Cache leeren",
        "cache_cleared" to "Offline-Room-Cache wurde geleert",
        "download_book_offline" to "Buch für Offline-Nutzung herunterladen",
        "downloading_offline" to "Kapitel werden in die Offline-Datenbank geladen...",
        "book_downloaded" to "Buch erfolgreich im Offline-Cache gespeichert",
        "check_updates" to "Nach GitHub-Updates suchen",
        "checking_updates" to "Suche nach Updates...",
        "update_available" to "Neue Version verfügbar!",
        "up_to_date" to "Sie verwenden die neueste Version",
        "download_update" to "Herunterladen und aktualisieren (APK)",
        "release_notes" to "Änderungsprotokoll",
        "comparison_count" to "Anzahl verglichener Übersetzungen (2-6):"
    )

    fun get(key: String, language: String): String {
        val dict = when (language.lowercase()) {
            "pl" -> pl
            "de" -> de
            else -> en
        }
        return dict[key] ?: en[key] ?: pl[key] ?: key
    }
}
