package com.example.ui.util

object Strings {
    private val pl = mapOf(
        "about" to "O programie",
        "about_desc" to "rBiblia to wieloprzekładowy czytnik Pisma Świętego z zaawansowaną porównywarką wersetów, czytaniem równoległym, notatkami i szybkim wyszukiwaniem.",
        "add_note" to "Dodaj notatkę",
        "all_translations" to "Wszystkie tłumaczenia",
        "cancel" to "Anuluj",
        "chapter_comparison" to "Porównanie rozdziałów",
        "clear_history" to "Wyczyść historię",
        "compare_verse" to "Porównaj werset",
        "copied" to "Skopiowano do schowka",
        "copy_report" to "Kopiuj zgłoszenie",
        "dark_variant" to "Wariant ciemnego motywu",
        "deuterocanonical" to "Księgi deuterokanoniczne",
        "edit_note" to "Edytuj notatkę",
        "error_type" to "Rodzaj błędu",
        "favorites" to "Ulubione",
        "font_family" to "Krój czcionki",
        "global_note" to "Notatka ogólna (dla wszystkich przekładów)",
        "hide" to "Ukryj",
        "language" to "Język aplikacji",
        "layout_continuous" to "Tekst ciągły",
        "layout_split" to "Podział na wersety",
        "new_testament" to "Nowy Testament",
        "next_chapter" to "Następny rozdział",
        "no_results" to "Brak wyników wyszukiwania",
        "note_placeholder" to "Wpisz treść notatki...",
        "notes" to "Notatki",
        "old_testament" to "Stary Testament",
        "prev_chapter" to "Poprzedni rozdział",
        "recent_searches" to "Ostatnie wyszukiwania",
        "report_comment" to "Komentarz / opis błędu",
        "reporter_email" to "Twój e-mail (opcjonalnie)",
        "reporter_name" to "Twoje imię / nick",
        "report_error" to "Zgłoś błąd w tekście",
        "results_found" to "Znaleziono",
        "save_note" to "Zapisz notatkę",
        "search" to "Szukaj w Biblii",
        "search_hint" to "Wpisz szukane słowo lub frazę...",
        "select_book" to "Wybierz księgę",
        "select_chapter" to "Wybierz rozdział",
        "settings" to "Ustawienia",
        "show" to "Pokaż",
        "show_differences" to "Wyróżnij różnice między przekładami",
        "submit_report" to "Wyślij zgłoszenie",
        "suggested_text" to "Poprawny tekst wersetu",
        "text_size" to "Rozmiar tekstu",
        "theme" to "Motyw kolorystyczny",
        "translations" to "Przekłady Biblii",
        "type_inaccuracy" to "Niedokładność tłumaczenia",
        "type_missing" to "Brakujący fragment",
        "type_punct" to "Błąd interpunkcyjny",
        "type_typo" to "Literówka / błąd ortograficzny",
        "verse_layout" to "Układ tekstu",
        "verse_numbers" to "Numery wersetów",
        "zen_mode" to "Tryb Zen (pełny ekran)",
        "zen_mode_hint" to "Maksymalna przestrzeń do czytania bez rozpraszaczy",
        "lang_all" to "Wszystkie",
        "lang_pl" to "Polski",
        "lang_en" to "English",
        "lang_de" to "Deutsch",
        "filter_by_language" to "Język przekładu",
        "parallel_reading" to "Czytanie równoległe",
        "parallel_mode_hint" to "Porównuj dwa przekłady symultanicznie",
        "select_parallel_translation" to "Wybierz drugi przekład",
        "parallel_columns" to "Dwie kolumny",
        "parallel_stacked" to "Wiersz pod wierszem",
        "swap_translations" to "Zamień przekłady",
        "parallel_missing_book" to "Ten przekład nie zawiera bieżącej księgi",
        "highlight_diff" to "Różnice"
    )

    private val en = mapOf(
        "about" to "About",
        "about_desc" to "rBiblia is a multi-translation Holy Bible reader with verse comparison, parallel reading, personal notes, and fast search.",
        "add_note" to "Add Note",
        "all_translations" to "All Translations",
        "cancel" to "Cancel",
        "chapter_comparison" to "Chapter Comparison",
        "clear_history" to "Clear History",
        "compare_verse" to "Compare Verse",
        "copied" to "Copied to clipboard",
        "copy_report" to "Copy Report",
        "dark_variant" to "Dark Theme Style",
        "deuterocanonical" to "Deuterocanonical",
        "edit_note" to "Edit Note",
        "error_type" to "Error Type",
        "favorites" to "Favorites",
        "font_family" to "Font Family",
        "global_note" to "Global Note (for all translations)",
        "hide" to "Hide",
        "language" to "App Language",
        "layout_continuous" to "Continuous Text",
        "layout_split" to "Verse by Verse",
        "new_testament" to "New Testament",
        "next_chapter" to "Next Chapter",
        "no_results" to "No results found",
        "note_placeholder" to "Write your note here...",
        "notes" to "Notes",
        "old_testament" to "Old Testament",
        "prev_chapter" to "Previous Chapter",
        "recent_searches" to "Recent Searches",
        "report_comment" to "Notes / Comments",
        "reporter_email" to "Your Email (optional)",
        "reporter_name" to "Your Name / Nickname",
        "report_error" to "Report Text Error",
        "results_found" to "Results found",
        "save_note" to "Save Note",
        "search" to "Search Bible",
        "search_hint" to "Search for word or phrase...",
        "select_book" to "Select Book",
        "select_chapter" to "Select Chapter",
        "settings" to "Settings",
        "show" to "Show",
        "show_differences" to "Highlight Differences",
        "submit_report" to "Submit Report",
        "suggested_text" to "Suggested Correct Text",
        "text_size" to "Text Size",
        "theme" to "Color Theme",
        "translations" to "Bible Translations",
        "type_inaccuracy" to "Translation Inaccuracy",
        "type_missing" to "Missing Text",
        "type_punct" to "Punctuation Error",
        "type_typo" to "Typo / Spelling",
        "verse_layout" to "Verse Layout",
        "verse_numbers" to "Verse Numbers",
        "zen_mode" to "Zen Mode",
        "zen_mode_hint" to "Minimalist reading experience",
        "lang_all" to "All",
        "lang_pl" to "Polish",
        "lang_en" to "English",
        "lang_de" to "German",
        "filter_by_language" to "Translation Language",
        "parallel_reading" to "Parallel Reading",
        "parallel_mode_hint" to "Read two translations side-by-side",
        "select_parallel_translation" to "Select Second Translation",
        "parallel_columns" to "Two Columns",
        "parallel_stacked" to "Stacked Rows",
        "swap_translations" to "Swap Translations",
        "parallel_missing_book" to "This translation does not contain current book",
        "highlight_diff" to "Differences"
    )

    private val de = mapOf(
        "about" to "Über das Programm",
        "about_desc" to "rBiblia ist ein mehrsprachiger Bibel-Reader mit Versvergleich, Parallellesemodus, Notizen und schneller Suche.",
        "add_note" to "Notiz hinzufügen",
        "all_translations" to "Alle Übersetzungen",
        "cancel" to "Abbrechen",
        "chapter_comparison" to "Kapitelvergleich",
        "clear_history" to "Verlauf löschen",
        "compare_verse" to "Vers vergleichen",
        "copied" to "In die Zwischenablage kopiert",
        "copy_report" to "Bericht kopieren",
        "dark_variant" to "Dunkles Design",
        "deuterocanonical" to "Spätschriften",
        "edit_note" to "Notiz bearbeiten",
        "error_type" to "Fehlertyp",
        "favorites" to "Favoriten",
        "font_family" to "Schriftart",
        "global_note" to "Globale Notiz (für alle Übersetzungen)",
        "hide" to "Ausblenden",
        "language" to "App-Sprache",
        "layout_continuous" to "Fließtext",
        "layout_split" to "Vers für Vers",
        "new_testament" to "Neues Testament",
        "next_chapter" to "Nächstes Kapitel",
        "no_results" to "Keine Ergebnisse gefunden",
        "note_placeholder" to "Notiz eingeben...",
        "notes" to "Notizen",
        "old_testament" to "Altes Testament",
        "prev_chapter" to "Vorheriges Kapitel",
        "recent_searches" to "Letzte Suchen",
        "report_comment" to "Kommentar",
        "reporter_email" to "Ihre E-Mail",
        "reporter_name" to "Ihr Name",
        "report_error" to "Fehler melden",
        "results_found" to "Gefunden",
        "save_note" to "Notiz speichern",
        "search" to "Bibel durchsuchen",
        "search_hint" to "Suchbegriff eingeben...",
        "select_book" to "Buch auswählen",
        "select_chapter" to "Kapitel auswählen",
        "settings" to "Einstellungen",
        "show" to "Anzeigen",
        "show_differences" to "Unterschiede hervorheben",
        "submit_report" to "Bericht senden",
        "suggested_text" to "Korrekturvorschlag",
        "text_size" to "Textgröße",
        "theme" to "Farbthema",
        "translations" to "Bibelübersetzungen",
        "type_inaccuracy" to "Ungenauigkeit",
        "type_missing" to "Fehlender Text",
        "type_punct" to "Satzzeichenfehler",
        "type_typo" to "Tippfehler",
        "verse_layout" to "Textanordnung",
        "verse_numbers" to "Versnummern",
        "zen_mode" to "Zen-Modus",
        "zen_mode_hint" to "Ablenkungsfreies Lesen",
        "lang_all" to "Alle",
        "lang_pl" to "Polnisch",
        "lang_en" to "Englisch",
        "lang_de" to "Deutsch",
        "filter_by_language" to "Sprache der Übersetzung",
        "parallel_reading" to "Paralleles Lesen",
        "parallel_mode_hint" to "Zwei Übersetzungen nebeneinander lesen",
        "select_parallel_translation" to "Zweite Übersetzung wählen",
        "parallel_columns" to "Zwei Spalten",
        "parallel_stacked" to "Zeile unter Zeile",
        "swap_translations" to "Übersetzungen tauschen",
        "parallel_missing_book" to "Diese Übersetzung enthält das aktuelle Buch nicht",
        "highlight_diff" to "Unterschiede"
    )

    fun get(key: String, language: String): String {
        val dict = when (language.lowercase()) {
            "pl" -> pl
            "de" -> de
            else -> en
        }
        return dict[key] ?: en[key] ?: pl[key] ?: key
    }
}
